# Generated by Django 5.1.1 on 2024-12-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
