# Generated by Django 5.1.1 on 2024-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0002_alter_candidate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father', models.CharField(max_length=100)),
                ('Phone_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Aadhaar_no', models.IntegerField()),
                ('Pan_no', models.IntegerField()),
                ('dob', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
