# Generated by Django 4.1.13 on 2024-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0003_personal_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_name', models.CharField(max_length=100)),
                ('Fathers_name', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Qualification_10th', models.CharField(max_length=50)),
                ('Qualification_12th', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('Tenth_percentage', models.FloatField(blank=True, null=True)),
                ('Twelfth_percentage', models.FloatField(blank=True, null=True)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Pincode', models.CharField(max_length=6)),
                ('Caste', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('UR', 'Unreserved')], max_length=3)),
                ('Religion', models.CharField(choices=[('Christian', 'Christian'), ('Hindhu', 'Hindhu'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=20)),
                ('Address', models.TextField()),
                ('Landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('Height', models.FloatField(help_text='Height in cm')),
                ('Weight', models.FloatField(help_text='Weight in kg')),
                ('Chest_size', models.FloatField(help_text='Size in cm')),
                ('Sports', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Ncc', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
