# Generated by Django 4.1.13 on 2024-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0004_specialregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialregistration',
            name='Highest_qua',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'UG'), ('PG', 'PG')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
