# Generated by Django 4.1.13 on 2024-12-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0005_specialregistration_highest_qua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialregistration',
            name='Qualification_10th',
        ),
        migrations.RemoveField(
            model_name='specialregistration',
            name='Qualification_12th',
        ),
        migrations.RemoveField(
            model_name='specialregistration',
            name='Qualification_degree',
        ),
        migrations.AddField(
            model_name='specialregistration',
            name='PG_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialregistration',
            name='UG_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialregistration',
            name='Highest_qua',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'UG'), ('PG', 'PG')], max_length=20),
        ),
    ]
