# Generated by Django 5.1.4 on 2024-12-28 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0006_remove_specialregistration_qualification_10th_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialregistration',
            name='Password',
        ),
        migrations.AddField(
            model_name='specialregistration',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.candidate'),
        ),
    ]
