# Generated by Django 5.1.4 on 2024-12-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0007_remove_specialregistration_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_details',
        ),
    ]
