# Generated by Django 5.1.4 on 2024-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0008_delete_personal_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.IntegerField(max_length=12)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Field', models.CharField(max_length=300)),
            ],
        ),
    ]
