# Generated by Django 5.1.4 on 2024-12-29 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0009_experts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='Contact',
            field=models.IntegerField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid contact number.')]),
        ),
    ]
