# Generated by Django 5.1.4 on 2024-12-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0010_alter_experts_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experts',
        ),
    ]
