# Generated by Django 5.1.4 on 2024-12-29 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0011_delete_experts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.IntegerField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid contact number.')])),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Field', models.CharField(max_length=300)),
            ],
        ),
    ]
