# Generated by Django 5.1.4 on 2024-12-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0012_experts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experts',
        ),
    ]
