# Generated by Django 5.1.4 on 2024-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0014_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
