# Generated by Django 5.1.4 on 2025-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0015_expert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='Achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='Designation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='LinkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='expert',
            name='Year_of_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
