# Generated by Django 5.1.4 on 2025-01-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0018_alter_appoinment_current_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Subject', models.CharField(max_length=1000)),
                ('complaint', models.CharField(max_length=1000)),
            ],
        ),
    ]
