# Generated by Django 5.1.4 on 2025-01-05 13:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0019_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='login_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ParserX.candidate'),
        ),
    ]
