# Generated by Django 5.1.4 on 2025-01-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0023_delete_tip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
