# Generated by Django 5.1.4 on 2025-01-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0024_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('Tips', models.CharField(max_length=5000)),
                ('ex_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.expert')),
            ],
        ),
    ]
