# Generated by Django 5.1.1 on 2025-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0025_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_materials',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=1000)),
                ('Topic', models.CharField(max_length=1000)),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
