# Generated by Django 5.1.1 on 2025-01-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0026_study_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_materials',
            name='File_upload',
            field=models.FileField(default=0, upload_to='upload'),
            preserve_default=False,
        ),
    ]
