# Generated by Django 5.1.4 on 2025-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0027_study_materials_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='conferencing_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='videocon_url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
