# Generated by Django 5.1.4 on 2025-01-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0028_appoinment_conferencing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=2000)),
                ('Salary', models.CharField(max_length=1000)),
                ('Date_of_Application', models.CharField(max_length=1000)),
                ('Last_date_of_application', models.CharField(max_length=1000)),
                ('Qualification', models.CharField(max_length=2000)),
                ('Experience', models.CharField(max_length=1000)),
                ('Date', models.DateField(null=True)),
            ],
        ),
    ]
