# Generated by Django 5.1.4 on 2025-01-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0029_vaccancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('sp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.specialregistration')),
                ('vaccancy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.vaccancy')),
            ],
        ),
    ]
