# Generated by Django 5.1.4 on 2025-01-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0031_remove_apply_vaccancy_sp_id_apply_vaccancy_can_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccancy',
            name='cad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.candidate'),
        ),
    ]
