# Generated by Django 5.1.4 on 2025-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0032_vaccancy_cad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccancy',
            name='applied_candidtaes',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
