# Generated by Django 5.1.4 on 2025-01-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0033_vaccancy_applied_candidtaes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccancy',
            old_name='applied_candidtaes',
            new_name='applied_candidates',
        ),
    ]
