# Generated by Django 5.1.4 on 2025-01-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0034_rename_applied_candidtaes_vaccancy_applied_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccancy',
            name='applied_candidates',
        ),
    ]
