# Generated by Django 5.1.4 on 2025-01-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0035_remove_vaccancy_applied_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_vaccancy',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
