# Generated by Django 5.1.1 on 2025-01-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0036_apply_vaccancy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('Notification', models.CharField(max_length=2000)),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
