# Generated by Django 5.1.1 on 2025-01-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0037_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Notification',
            new_name='Notifications',
        ),
    ]
