# Generated by Django 5.1.1 on 2025-01-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0039_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
