# Generated by Django 5.1.1 on 2025-01-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0041_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='field',
            field=models.CharField(choices=[('UPSC', 'UPSC'), ('SSC', 'SSC'), ('IBPS', 'IBPS'), ('CBSE', 'CBSE'), ('RBI', 'RBI'), ('RRB', 'RRB'), ('DEFENCE', 'DEFENCE'), ('Others', 'Others')], max_length=50),
        ),
    ]
