# Generated by Django 5.1.1 on 2025-01-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0042_alter_resource_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccancy',
            name='Qualification',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'UG'), ('PG', 'PG')], max_length=2000),
        ),
    ]
