# Generated by Django 5.1.1 on 2025-02-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0045_mocktest_question_option_testresult_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mock_test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='MockTest',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
