# Generated by Django 5.1.1 on 2025-02-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0046_remove_userresponse_test_remove_question_mock_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commpany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_category', models.CharField(max_length=200)),
                ('Business_name', models.CharField(max_length=200)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
