# Generated by Django 5.1.1 on 2025-02-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0047_commpany'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commpany',
            new_name='Company',
        ),
    ]
