# Generated by Django 5.1.1 on 2025-02-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0048_rename_commpany_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='com_status',
            field=models.IntegerField(default=0),
        ),
    ]
