# Generated by Django 5.1.1 on 2025-02-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0049_candidate_com_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='com_status',
        ),
    ]
