# Generated by Django 5.1.1 on 2025-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0050_remove_candidate_com_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='com_status',
            field=models.IntegerField(default=0),
        ),
    ]
