# Generated by Django 5.1.1 on 2025-02-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0051_company_com_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('candidate_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatereceived_messages', to='ParserX.candidate')),
                ('candidate_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatesent_messages', to='ParserX.candidate')),
                ('expert_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_received_messages', to='ParserX.expert')),
                ('expert_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_sent_messages', to='ParserX.expert')),
            ],
        ),
    ]
