# Generated by Django 5.1.1 on 2025-02-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0053_category_exam_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
