# Generated by Django 5.1.1 on 2025-02-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0057_company_vaccancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_vaccancy',
        ),
    ]
