# Generated by Django 5.1.1 on 2025-02-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0058_delete_company_vaccancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_category', models.CharField(max_length=100)),
                ('Job_name', models.CharField(max_length=100)),
                ('Job_description', models.CharField(max_length=500)),
                ('Last_date_for_apply', models.DateField(null=True)),
                ('Qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
