# Generated by Django 5.1.1 on 2025-02-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0059_company_vaccancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.company'),
        ),
    ]
