# Generated by Django 5.1.1 on 2025-02-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0060_company_vaccancy_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='private_Apply_vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('private_can_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.candidate')),
                ('private_vaccancy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.company_vaccancy')),
            ],
        ),
    ]
