# Generated by Django 5.1.1 on 2025-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0061_private_apply_vaccancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_apply_vaccancy',
            name='cancel_status',
            field=models.IntegerField(default=0),
        ),
    ]
