# Generated by Django 5.1.1 on 2025-02-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0062_private_apply_vaccancy_cancel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_apply_vaccancy',
            name='cancel_status',
        ),
    ]
