# Generated by Django 5.1.1 on 2025-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0063_remove_private_apply_vaccancy_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='cancel_status',
            field=models.IntegerField(default=0),
        ),
    ]
