# Generated by Django 5.1.1 on 2025-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0065_remove_company_vaccancy_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
