# Generated by Django 5.1.3 on 2025-02-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0066_company_vaccancy_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private_apply_vaccancy',
            old_name='status',
            new_name='p_status',
        ),
    ]
