# Generated by Django 5.1.3 on 2025-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0069_private_apply_vaccancy_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
