# Generated by Django 5.1.3 on 2025-02-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0070_company_vaccancy_interview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_vaccancy',
            name='interview_date',
        ),
    ]
