# Generated by Django 5.1.3 on 2025-02-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0072_company_vaccancy_interview_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='videocon_url2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
