# Generated by Django 5.1.3 on 2025-02-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0073_company_vaccancy_videocon_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='conferencing_status',
            field=models.IntegerField(default=0),
        ),
    ]
