# Generated by Django 5.1.3 on 2025-02-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0074_company_vaccancy_conferencing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_vaccancy',
            name='videocon_url2',
        ),
    ]
