# Generated by Django 5.1.3 on 2025-02-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0075_remove_company_vaccancy_videocon_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vaccancy',
            name='videocon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
