# Generated by Django 5.1.6 on 2025-03-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0077_mcq_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
