# Generated by Django 5.1.6 on 2025-03-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0079_mcq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccancy',
            name='cad',
        ),
        migrations.DeleteModel(
            name='Apply_vaccancy',
        ),
        migrations.DeleteModel(
            name='Vaccancy',
        ),
    ]
