# Generated by Django 5.1.6 on 2025-03-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0082_delete_specialregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_name', models.CharField(max_length=100)),
                ('Fathers_name', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('Highest_qua', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'UG'), ('PG', 'PG')], max_length=20)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Caste', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('UR', 'Unreserved')], max_length=3)),
                ('Height', models.FloatField(help_text='Height in cm')),
                ('Weight', models.FloatField(help_text='Weight in kg')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParserX.candidate')),
            ],
        ),
    ]
