# Generated by Django 5.1.7 on 2025-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0083_specialregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialregistration',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
