# Generated by Django 5.1.7 on 2025-03-15 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0084_specialregistration_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Contact',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid contact number.')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='Contact',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid contact number.')]),
        ),
        migrations.AlterField(
            model_name='expert',
            name='Contact',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid contact number.')]),
        ),
        migrations.AlterField(
            model_name='specialregistration',
            name='Phone_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid contact number.')]),
        ),
    ]
