# Generated by Django 5.1.7 on 2025-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0085_alter_candidate_contact_alter_company_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialregistration',
            name='nationality',
            field=models.CharField(choices=[('IND', 'Indian'), ('OTH', 'Other')], default='IND', max_length=3),
        ),
    ]
