# Generated by Django 5.1.7 on 2025-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0086_specialregistration_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialregistration',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], default='S', max_length=1),
        ),
    ]
