# Generated by Django 5.1.7 on 2025-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0087_specialregistration_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialregistration',
            name='languages_known',
            field=models.CharField(default='hindi', help_text='Enter languages known, separated by commas (e.g., English, Hindi, Tamil)', max_length=200),
        ),
    ]
