# Generated by Django 5.1.7 on 2025-03-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0088_specialregistration_languages_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialregistration',
            name='disability_status',
            field=models.CharField(choices=[('No', 'No Disability'), ('Yes', 'Person with Disability (PwD)')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='specialregistration',
            name='languages_known',
            field=models.CharField(default='English', help_text='Enter languages known, separated by commas (e.g., English, Hindi, Tamil)', max_length=200),
        ),
    ]
