# Generated by Django 5.1.7 on 2025-03-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0089_specialregistration_disability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialregistration',
            name='profile_photo',
        ),
    ]
