# Generated by Django 5.1.1 on 2025-03-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0090_remove_specialregistration_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
