# Generated by Django 5.1.1 on 2025-03-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParserX', '0091_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralgovjob',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
