from django.urls import path
from . import views


urlpatterns=[
    path('',views.Home,name='Home'),
    path('admin1/',views.admin1,name='admin1'),
    path('login/',views.login,name='login'),
    path('user_page/',views.user_page,name='user_page'),
    path('candidate/',views.candidate,name='candidate'),
    path('user_header/',views.user_header,name='user_header'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('special_register/',views.SpecialRegistration_view, name='SpecialRegistration_view'),
    # path('special-registration/', views.SpecialRegistration_view, name='special_registration_view'),
    path('special-registration/', views.SpecialRegistration_view, name='special_registration'),
    path('Sprofile_view/', views.Sprofile_view, name='Sprofile_view'),
    path('success/', views.success_view, name='success'),
    # path('profile_view/', views.profile_view, name='profile_view'),
    path('edit_special_profile/<int:id>/', views.edit_special_profile, name='edit_special_profile'),
    path('delete_special_profile/<int:id>/', views.delete_special_profile, name='delete_special_profile'),
    path('experts/', views.experts, name='experts'),
    path('admin1/table-datatable/', views.expert_view, name='expert_view'),
    path('accept/<int:pk>/', views.accept,name='accept'),
    path('reject/<int:pk>', views.reject, name='reject'),
    path('expert_login/', views.expert_login, name='expert_login'),
    path('admin_header/',views.admin_header,name='admin_header'),
    path('video_conference/<int:pk>/',views.video_conference,name='video_conference'),
    path('expert_header/',views.expert_header,name='expert_header'),
    path('search/', views.search, name='search'),
    path('Appoinment/<int:id>/',views.appointment,name='Appoinment'),
    path('expert_home/',views.expert_home,name='expert_home'),
    path('appoint_view/',views.appoint_view,name='appoint_view'),
    path('user_appoint/',views.user_appoint,name='user_appoint'),
    path('edit_appoinment/<int:id>/',views.edit_appoinment,name='edit_appoinment'),
    path('cad_cancel/<int:id>/',views.cad_cancel,name='cad_cancel'),
    path('complaint/',views.complaint,name='complaint'),
    path('user_complaint/',views.user_complaint,name='user_complaint'),
    path('delete_complaints/<int:id>',views.delete_complaints,name='delete_complaints'),
    path('edit_complaints/<int:id>',views.edit_complaints,name='edit_complaints'),
    path('Response/<int:id>',views.Response,name='Response'),
    path('Tip/', views.Tip, name='Tip'),
    path('tip_view/',views.tip_view,name='tip_view'),
    path('edit_tview/<int:id>/',views.edit_tview,name='edit_tview'),
    path('remove_tips/<int:id>/',views.remove_tips,name='remove_tips'),
    path('ct_view/',views.ct_view,name='ct_view'),
    path('study_materials/', views.study_materials, name='study_materials'),
    path('fetch_topics/', views.fetch_topics, name='fetch_topics'),
    path('materials_view/',views.materials_view,name='materials_view'),
    path('download/<int:file_id>/', views.download_file, name='download_file'),
    path('edit_study_material/<int:id>/', views.edit_study_material, name='edit_study_material'),
    path('delete_study_material/<int:id>/', views.delete_study_material, name='delete_study_material'),
    path('study_materials_display/', views.study_materials_display, name='study_materials_display'),
    path('download_file/<int:file_id>/', views.download_file, name='download_file'),
    path('save_appointment_url/<int:pk>/',views.save_appointment_url, name='save_appointment_url'),
    path('add-job/', views.add_central_gov_job, name='add_central_gov_job'),
    # path('vaccancy/',views.vaccancy,name='vaccancy'),
    path('view-jobs/', views.central_gov_jobs_view, name='central_gov_jobs_view'),
    # path('vaccancy_view/',views.vaccancy_view,name='vaccancy_view'),
    # path('edit_vaccancy/<int:id>/',views.edit_vaccancy,name='edit_vaccancy'),
    # path('remove_vaccancy/<int:id>/',views.remove_vaccancy,name='remove_vaccancy'),
    path('apply/<int:id>/',views.apply,name='apply'),
    path('can_vaccancy/',views.can_vaccancy,name='can_vaccancy'),
    path('view-jobs/', views.central_gov_jobs_view, name='central_gov_jobs_view'),
    path('edit-job/<int:id>/', views.edit_central_gov_job, name='edit_central_gov_job'),
    path('delete-job/<int:id>/', views.delete_central_gov_job, name='delete_central_gov_job'),
    # path('vacancy/<int:vaccancy_id>/applicants/', views.vacancy_applicants_view, name='vacancy_applicants'),
    # path('candidate_jobs_view/', views.candidate_jobs_view, name='candidate_jobs_view'),
    # path('cancel-application/<int:application_id>/', views.cancel_application, name='cancel_application'),
    # path('vacancy/<int:vacancy_id>/applicants/', views.vacancy_applicants_view, name='view_applicants'),
    # path('vacancy/<int:vacancy_id>/applicants/', views.applicants_view, name='applicants_view'),
    path('add_notification/',views.add_notification,name='add_notification'),
    path('notification_list/',views.notification_list,name='notification_list'),
    path('edit_notification/<int:id>/',views.edit_notification,name='edit_notification'),
    path('remove_notification/<int:id>/',views.remove_notification,name='remove_notification'),
    path('notify_list/',views.notify_list,name='notify_list'),
    path('add_resource/', views.add_resource, name='add_resource'),
    path('resources/',views.resources,name='resources'),
    path('select_field/', views.select_field, name='select_field'),  # Field selection page
    path('resources_by_field/<str:field_name>/',views.resources_by_field,name='resources_by_field'),  # Resources for selected field
    path('recommend_jobs/', views.recommend_jobs, name='recommend_jobs'),
    path('edit_resource/<int:id>/',views.edit_resource,name='edit_resource'),
    path('remove_resources/<int:id>',views.remove_resources,name='remove_resources'),
    path('upload_resume/', views.upload_resume, name='upload_resume'),
    path('company/',views.company,name='company'),
    path('com_accept/<int:pk>/', views.com_accept,name='com_accept'),
    path('com_reject/<int:pk>', views.com_reject, name='com_reject'),
    path('chat_exp/<int:pk>/', views.chat_exp, name='chat_exp'),
    path('chat_temp/<int:pk>/',views.chat_temp,name='chat_temp'),
    path('chats_list/',views.chats_list,name='chats_list'),
    path('chat_list/',views.chat_list,name='chat_list'),
    path('company_page/',views.company_page,name='company_page'),
    path('com_login/',views.com_login,name='com_login'),
    path('company_profile/', views.company_profile, name='company_profile'),    
    path('edit_company/<int:id>/',views.edit_company,name='edit_company'), 
    path('remove_company/<int:id>/',views.remove_company,name='remove_company'),
    path('com_header/',views.com_header,name='com_header'),
    path('users_page/',views.users_page,name='users_page'),
    # path('sector_selection/',views.sector_selection,name='sector_selection'),
    path('com_vaccancy/',views.com_vaccancy,name='com_vaccancy'),
    path('private_vaccancy_view/',views.private_vaccancy_view,name='private_vaccancy_view'),
    path('edit_com_vaccancy/<int:id>/',views.edit_com_vaccancy,name='edit_com_vaccancy'),
    path('remove_com_vaccancy/<int:id>/',views.remove_com_vaccancy,name='remove_com_vaccancy'),
    path('private_can_vaccancy/',views.private_can_vaccancy,name='private_can_vaccancy'),
    path('private_apply/<int:id>/',views.private_apply,name='private_apply'),
    path('vacancy_detail/<int:id>/',views.vacancy_detail,name='vacancy_detail'),
    path('view_applicants/<int:id>/',views.view_applicants,name='view_applicants'),
    # path('view_applied_jobs/',views.view_applied_jobs,name='view_applied_jobs'),
    # path('cancel_status/<int:pk>/',views.cancel_status,name='cancel_status'),
    # path('private_vacancy_applicants_view/<int:private_vacancy_id>/', views.private_vacancy_applicants_view, name='private_vacancy_applicants'),
    # path('private_get_vacancy_applicants/<int:vaccancy_id>/', views.private_get_vacancy_applicants, name='private_get_vacancy_applicants'),
    path('view_applied_jobs/', views.view_applied_jobs, name='view_applied_jobs'),
    path('private_cancel_application/<int:application_id>/', views.private_cancel_application, name='private_cancel_application'),
    path('announce_interview/<int:id>/', views.announce_interview, name='announce_interview'),

    #interview video conferece
    # path('video-conference/<int:pk>/', views.video_conference_company, name='video_conference_company'),
    # path('interview-url/<int:pk>/', views.interview_url, name='interview_url'),
    path('video_conference_company/<int:id>/', views.video_conference_company, name='video_conference_company'),
    path('interview-url/<int:id>/', views.interview_url, name='interview_url'),


    path("latest-exams/", views.fetch_exam_dates, name="latest_exams"),
    path("defence-exams/", views.defence_exams, name="defence_exams"),

    path("ppage/", views.ppage, name="ppage"),


    # path("mcq_view/",views.mcq_view, name="mcq_view"),
    # path('api/mcq/<str:category>/', views.get_mcqs, name='get_mcqs'),
    # path('mcq-test/', views.mcq_test, name='mcq_test'),

    # path('clear-tip/', views.clear_tip, name='clear_tip'),
    path("api/mcq/<str:category>/", views.get_mcqs, name="get_mcqs"),
    path("api/categories/", views.get_categories, name="get_categories"),
    path("mcq-test/", views.mcq_test, name="mcq_test"),
]


    
